performance mods based on libresdr

diff --git a/patches/buildroot.diff b/patches/buildroot.diff
--- a/patches/buildroot.diff
+++ b/patches/buildroot.diff
@@ -1,7 +1,52 @@
+diff --git a/board/pluto/S23udc b/board/pluto/S23udc
+index 202347f0..049124b1 100644
+--- a/board/pluto/S23udc
++++ b/board/pluto/S23udc
+@@ -118,7 +118,8 @@ case "$1" in
+ 	mkdir -p /dev/iio_ffs
+ 	mount iio_ffs -t functionfs /dev/iio_ffs 2> /dev/null
+ 
+-	start-stop-daemon -S -b -q -m -p /var/run/iiod.pid -x  /usr/sbin/iiod  -- $IIOD_OPTS
++	#start-stop-daemon -S -b -q -m -p /var/run/iiod.pid -x  /usr/sbin/iiod  -- $IIOD_OPTS
++        start-stop-daemon -S -b -q -m -p /var/run/iiod.pid -x /usr/bin/chrt -- -r 99 /usr/bin/taskset -c 1 /usr/sbin/iiod $IIOD_OPTS
+ 	sleep 0.2
+ 
+ 	echo ci_hdrc.0 > $GADGET/UDC
+diff --git a/board/pluto/S41network b/board/pluto/S41network
+index 78433a60..954284ad 100644
+--- a/board/pluto/S41network
++++ b/board/pluto/S41network
+@@ -7,13 +7,13 @@ case "$1" in
+ 	start)
+ 		echo -n "Starting dhcpd Daemon & httpd Server: "
+ 		start-stop-daemon -S -q -p /var/run/udhcpd.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF
+-		httpd -h /www
++		#httpd -h /www
+ 		[ $? = 0 ] && echo "OK" || echo "FAIL"
+ 		;;
+ 
+ 	stop)
+ 		echo -n "Stopping dhcpd Daemon & httpd Server: "
+-		killall -7 httpd
++		#killall -7 httpd
+ 		start-stop-daemon -K -q -p /var/run/udhcpd.pid 2>/dev/null
+ 		[ $? = 0 ] && echo "OK" || echo "FAIL"
+ 		;;
 diff --git a/board/pluto/busybox-1.25.0.config b/board/pluto/busybox-1.25.0.config
-index 88728cc9..78cf61c0 100644
+index 88728cc9..15493831 100644
 --- a/board/pluto/busybox-1.25.0.config
 +++ b/board/pluto/busybox-1.25.0.config
+@@ -669,8 +669,8 @@ CONFIG_SWAPON=y
+ # CONFIG_FEATURE_SWAPON_PRI is not set
+ CONFIG_SWAPOFF=y
+ CONFIG_SWITCH_ROOT=y
+-# CONFIG_TASKSET is not set
+-# CONFIG_FEATURE_TASKSET_FANCY is not set
++CONFIG_TASKSET=y
++CONFIG_FEATURE_TASKSET_FANCY=y
+ CONFIG_UEVENT=y
+ CONFIG_UMOUNT=y
+ CONFIG_FEATURE_UMOUNT_ALL=y
 @@ -880,10 +880,10 @@ CONFIG_FEATURE_IP_NEIGH=y
  CONFIG_NAMEIF=y
  # CONFIG_FEATURE_NAMEIF_EXTENDED is not set
@@ -26,6 +71,21 @@ index 88728cc9..78cf61c0 100644
  # CONFIG_FEATURE_TUNCTL_UG is not set
  CONFIG_VCONFIG=y
  CONFIG_WGET=y
+@@ -1008,10 +1008,10 @@ CONFIG_TOP=y
+ CONFIG_FEATURE_TOP_INTERACTIVE=y
+ CONFIG_FEATURE_TOP_CPU_USAGE_PERCENTAGE=y
+ CONFIG_FEATURE_TOP_CPU_GLOBAL_PERCENTS=y
+-# CONFIG_FEATURE_TOP_SMP_CPU is not set
+-# CONFIG_FEATURE_TOP_DECIMALS is not set
+-# CONFIG_FEATURE_TOP_SMP_PROCESS is not set
+-# CONFIG_FEATURE_TOPMEM is not set
++CONFIG_FEATURE_TOP_SMP_CPU=y
++CONFIG_FEATURE_TOP_DECIMALS=y
++CONFIG_FEATURE_TOP_SMP_PROCESS=y
++CONFIG_FEATURE_TOPMEM=y
+ CONFIG_UPTIME=y
+ # CONFIG_FEATURE_UPTIME_UTMP_SUPPORT is not set
+ CONFIG_WATCH=y
 diff --git a/board/pluto/motd b/board/pluto/motd
 index a3b3f6f6..55601033 100644
 --- a/board/pluto/motd
@@ -48,18 +108,23 @@ index a3b3f6f6..55601033 100644
 -https://wiki.analog.com/university/tools/pluto
 +https://github.com/plutoplus/plutoplus
 diff --git a/configs/zynq_pluto_defconfig b/configs/zynq_pluto_defconfig
-index 6203766e..792a9e98 100644
+index 6203766e..1c5660a7 100644
 --- a/configs/zynq_pluto_defconfig
 +++ b/configs/zynq_pluto_defconfig
-@@ -5,6 +5,7 @@ BR2_ARM_ENABLE_VFP=y
+@@ -5,7 +5,11 @@ BR2_ARM_ENABLE_VFP=y
  BR2_ARM_FPU_NEON=y
  BR2_TOOLCHAIN_EXTERNAL=y
  BR2_TOOLCHAIN_EXTERNAL_LINARO_ARM=y
+-BR2_OPTIMIZE_2=y
 +BR2_OPTIMIZE_3=y
- BR2_OPTIMIZE_2=y
++BR2_PACKAGE_ETHTOOL=y
++BR2_PACKAGE_ETHTOOL_PRETTY_PRINT=y
++BR2_PACKAGE_IPERF3=y
++BR2_PACKAGE_HTOP=y
  BR2_TARGET_GENERIC_HOSTNAME="pluto"
  BR2_TARGET_GENERIC_ISSUE="Welcome to Pluto"
-@@ -29,6 +30,7 @@ BR2_PACKAGE_MTD=y
+ BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_MDEV=y
+@@ -29,6 +33,7 @@ BR2_PACKAGE_MTD=y
  # BR2_PACKAGE_MTD_UBIRSVOL is not set
  # BR2_PACKAGE_MTD_UBIUPDATEVOL is not set
  # BR2_PACKAGE_MTD_UBIBLOCK is not set
@@ -67,7 +132,7 @@ index 6203766e..792a9e98 100644
  BR2_PACKAGE_LINUX_FIRMWARE=y
  BR2_PACKAGE_LINUX_FIRMWARE_RALINK_RT61=y
  BR2_PACKAGE_LINUX_FIRMWARE_RALINK_RT73=y
-@@ -36,24 +38,40 @@ BR2_PACKAGE_LINUX_FIRMWARE_RALINK_RT2XX=y
+@@ -36,24 +41,40 @@ BR2_PACKAGE_LINUX_FIRMWARE_RALINK_RT2XX=y
  BR2_PACKAGE_LINUX_FIRMWARE_RTL_81XX=y
  BR2_PACKAGE_LINUX_FIRMWARE_RTL_87XX=y
  BR2_PACKAGE_LINUX_FIRMWARE_RTL_88XX=y
@@ -109,7 +174,7 @@ index 6203766e..792a9e98 100644
  BR2_PACKAGE_POLL_SYSFS=y
  BR2_PACKAGE_AD936X_REF_CAL=y
  BR2_TARGET_ROOTFS_CPIO=y
-@@ -62,3 +80,29 @@ BR2_TARGET_ROOTFS_CPIO_UIMAGE=y
+@@ -62,3 +83,29 @@ BR2_TARGET_ROOTFS_CPIO_UIMAGE=y
  BR2_PACKAGE_HOST_DOSFSTOOLS=y
  BR2_PACKAGE_HOST_GENIMAGE=y
  BR2_PACKAGE_HOST_MTOOLS=y
@@ -139,54 +204,6 @@ index 6203766e..792a9e98 100644
 +BR2_PACKAGE_VALGRIND_CALLGRIND=y
 +BR2_PACKAGE_LINUX_TOOLS_PERF=y
 +
-diff --git a/package/libfec/Config.in b/package/libfec/Config.in
-new file mode 100644
-index 00000000..8afd24a8
---- /dev/null
-+++ b/package/libfec/Config.in
-@@ -0,0 +1,5 @@
-+config BR2_PACKAGE_libfec
-+	bool "libfec"
-+	select BR2_PACKAGE_libfec
-+	help
-+	  libfec
-diff --git a/package/libfec/libfec.hash b/package/libfec/libfec.hash
-new file mode 100644
-index 00000000..819ea388
---- /dev/null
-+++ b/package/libfec/libfec.hash
-@@ -0,0 +1 @@
-+sha256	17484620f37614bd61e64189ed3a9908031ad0c18ba250756e8da8130c9cf068  libfec-0.2.tar.gz
-diff --git a/package/libfec/libfec.mk b/package/libfec/libfec.mk
-new file mode 100644
-index 00000000..a4300379
---- /dev/null
-+++ b/package/libfec/libfec.mk
-@@ -0,0 +1,24 @@
-+################################################################################
-+#
-+# libfec
-+#
-+################################################################################
-+LIBFEC_VERSION = 0.2
-+LIBFEC_SITE = $(call github,tvelliott,libfec,master)
-+
-+LIBFEC_INSTALL_STAGING = YES
-+
-+define LIBFEC_BUILD_CMDS
-+	$(TARGET_MAKE_ENV) CROSS_COMPILE=arm-linux-gnueabihf- $(MAKE1) -C $(@D)
-+endef
-+
-+define LIBFEC_INSTALL_TARGET_CMDS
-+	(cd $(@D); \
-+    cp *.so $(TARGET_DIR)/usr/lib/ ; \
-+    cp *.a $(TARGET_DIR)/usr/lib/ ; \
-+    cp fec.h $(STAGING_DIR)/usr/include/ ; \
-+    cp *.so $(STAGING_DIR)/usr/lib/ ; \
-+    )
-+endef
-+
-+$(eval $(generic-package))
 diff --git a/package/liquid-dsp/liquid-dsp.mk b/package/liquid-dsp/liquid-dsp.mk
 index fcdf5725..fbe3594a 100644
 --- a/package/liquid-dsp/liquid-dsp.mk
